{"uuid": "5a27d35c-8e90-44de-b8b5-42368320ddf9", "children": ["48ca6ea9-2aba-4399-a6e2-e887ce907b76"], "befores": [{"name": "driver", "status": "passed", "start": 1657875205317, "stop": 1657875206364}], "afters": [{"name": "driver::1", "status": "passed", "start": 1657875207733, "stop": 1657875207733}, {"name": "driver::tear_down", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: You clicked a button\nMessage: unexpected alert open: {Alert text : You clicked a button}\n  (Session info: chrome=103.0.5060.114)\nStacktrace:\n#0 0x555c4980cb13 <unknown>\n#1 0x555c49613688 <unknown>\n#2 0x555c4967b93b <unknown>\n#3 0x555c496687a3 <unknown>\n#4 0x555c4963e0ea <unknown>\n#5 0x555c4963f225 <unknown>\n#6 0x555c498542dd <unknown>\n#7 0x555c498582c7 <unknown>\n#8 0x555c4983e22e <unknown>\n#9 0x555c498590a8 <unknown>\n#10 0x555c49832bc0 <unknown>\n#11 0x555c498756c8 <unknown>\n#12 0x555c49875848 <unknown>\n#13 0x555c4988fc0d <unknown>\n#14 0x7f83597e2b43 <unknown>\n\n", "trace": "  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/alex/python/code/SeleniumPython/conftest.py\", line 94, in tear_down\n    allure.attach(driver.get_screenshot_as_png(), attachment_type=allure.attachment_type.PNG)\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 246, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1657875207733, "stop": 1657875207737}], "start": 1657875205317, "stop": 1657875207737}