{"uuid": "b5b8ece5-dcfa-4f8d-be28-39c06664cedb", "children": ["f58f8397-70c2-4a5c-bbcb-7ca8cf90e319"], "befores": [{"name": "driver", "status": "passed", "start": 1657875243466, "stop": 1657875244525}], "afters": [{"name": "driver::1", "status": "passed", "start": 1657875245991, "stop": 1657875245991}, {"name": "driver::tear_down", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: You clicked a button\nMessage: unexpected alert open: {Alert text : You clicked a button}\n  (Session info: chrome=103.0.5060.114)\nStacktrace:\n#0 0x5595415bcb13 <unknown>\n#1 0x5595413c3688 <unknown>\n#2 0x55954142b93b <unknown>\n#3 0x5595414187a3 <unknown>\n#4 0x5595413ee0ea <unknown>\n#5 0x5595413ef225 <unknown>\n#6 0x5595416042dd <unknown>\n#7 0x5595416082c7 <unknown>\n#8 0x5595415ee22e <unknown>\n#9 0x5595416090a8 <unknown>\n#10 0x5595415e2bc0 <unknown>\n#11 0x5595416256c8 <unknown>\n#12 0x559541625848 <unknown>\n#13 0x55954163fc0d <unknown>\n#14 0x7ff4796deb43 <unknown>\n\n", "trace": "  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/alex/python/code/SeleniumPython/conftest.py\", line 94, in tear_down\n    allure.attach(driver.get_screenshot_as_png(), attachment_type=allure.attachment_type.PNG)\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1357, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1369, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/home/alex/python/code/SeleniumPython/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 246, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1657875245991, "stop": 1657875245995}], "start": 1657875243465, "stop": 1657875245995}